# Libraries

In [45]:
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams.update({
                        'font.family': 'serif',
                        'mathtext.fontset': 'cm',
                        'axes.unicode_minus': False
                    })

# Model upload

In [46]:
name_best_model = 'models/model_HistGradientBoosting_fold_4.pkl'
model = joblib.load(name_best_model)

# Profile for test

### Data

In [47]:
CO2_ppm = 800               # Change as you wish. In ppm units        
fc = 30.0                   # Change as you wish. In MPa units 
rh = 35.4                   # Change as you wish. In % units
cement_type = 0             # Change as you wish. 0 to 5. CPII - Z=0, CPV - ARI=1, CPIV=2, CPII - F=3, CPIII=4, CPII - E=5
exposure_conditions = 0     # Change as you wish. 0 to 2. PIA=0, UEA=1, PEA=2

In [48]:
df = {'t (years)': list(range(1, 101))}
df = pd.DataFrame(df)
df['CO2 (%)'] = CO2_ppm / 10000
df['fc (MPa)'] = fc
df['RH (%)'] = rh
df['Type of cement'] = cement_type
df['Exposure conditions'] = exposure_conditions
expected_order = list(model.feature_names_in_)
df = df[expected_order]
df

    CO2 (%)  fc (MPa)  RH (%)  Type of cement  Exposure conditions  t (years)
0      0.08      30.0    35.4               0                    0          1
1      0.08      30.0    35.4               0                    0          2
2      0.08      30.0    35.4               0                    0          3
3      0.08      30.0    35.4               0                    0          4
4      0.08      30.0    35.4               0                    0          5
..      ...       ...     ...             ...                  ...        ...
95     0.08      30.0    35.4               0                    0         96
96     0.08      30.0    35.4               0                    0         97
97     0.08      30.0    35.4               0                    0         98
98     0.08      30.0    35.4               0                    0         99
99     0.08      30.0    35.4               0                    0        100

[100 rows x 6 columns]

### Creating profile

In [49]:
df_aux = df.copy()
y_pred = model.predict(df)
df_aux['carb. depth (mm)'] = list(y_pred)
df_aux

,CO2 (%),fc (MPa),RH (%),Type of cement,Exposure conditions,t (years),carb. depth (mm)
0,0.08,30.0,35.4,0,0,1,1.997072
1,0.08,30.0,35.4,0,0,2,3.501555
2,0.08,30.0,35.4,0,0,3,4.793465
3,0.08,30.0,35.4,0,0,4,5.047338
4,0.08,30.0,35.4,0,0,5,5.756616
...,...,...,...,...,...,...,...
95,0.08,30.0,35.4,0,0,96,25.783003
96,0.08,30.0,35.4,0,0,97,25.839307
97,0.08,30.0,35.4,0,0,98,25.839307
98,0.08,30.0,35.4,0,0,99,25.839307
99,0.08,30.0,35.4,0,0,100,25.839307