In [1]:
from obj import nowak_collins_time_example

In [8]:
# Libraries
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

from parepy_toolbox import sampling_algorithm_structural_analysis, sampling_algorithm_structural_analysis_kernel

# Statement random variables
f = {
        'type': 'normal', 
        'parameters': {'mean': 40.3, 'sigma': 4.64}, 
        'stochastic variable': False, 
    }

p = {
        'type': 'gumbel max',
        'parameters': {'mean': 10.2, 'sigma': 1.12}, 
        'stochastic variable': True, 
    }

w = {
        'type': 'lognormal',
        'parameters': {'mean': 0.25, 'sigma': 0.025}, 
        'stochastic variable': False, 
    }
var = [f, p, w]

# PAREpy setup
setup = {
             'number of samples': 1000, 
             'numerical model': {'model sampling': 'mcs-time', 'time steps': 5}, 
             'variables settings': var, 
             'number of state limit functions or constraints': 1, 
             'none variable': {'time analysis': list(np.linspace(0, 50, num=5, endpoint=True))},
             'objective function': nowak_collins_time_example,
             'name simulation': 'nowak_collins_time_example',
        }

# Call algorithm
results, pf, beta = sampling_algorithm_structural_analysis(setup)

10:51:03 - Checking inputs completed!
10:51:03 - Started State Limit Function evaluation (g)...
10:51:05 - Finished State Limit Function evaluation (g) in 2.68e+00 seconds!
10:51:05 - Started evaluation beta reliability index and failure probability...
10:51:05 - Finished evaluation beta reliability index and failure probability in 2.68e-02 seconds!
10:51:05 - Voilà!!!!....simulation results are saved in nowak_collins_time_example_MCS-TIME_20250319-105105.txt

In [3]:
results

,X_0_t=0,X_0_t=1,X_0_t=2,X_0_t=3,X_0_t=4,X_1_t=0,X_1_t=1,X_1_t=2,X_1_t=3,X_1_t=4,X_2_t=0,X_2_t=1,X_2_t=2,X_2_t=3,X_2_t=4,STEP_t_0,STEP_t_1,STEP_t_2,STEP_t_3,STEP_t_4,R_0_t=0,R_0_t=1,R_0_t=2,R_0_t=3,R_0_t=4,S_0_t=0,S_0_t=1,S_0_t=2,S_0_t=3,S_0_t=4,G_0_t=0,G_0_t=1,G_0_t=2,G_0_t=3,G_0_t=4,I_0_t=0,I_0_t=1,I_0_t=2,I_0_t=3,I_0_t=4
0,42.003185,42.003185,42.003185,42.003185,42.003185,12.445782,9.640208,10.013260,10.486451,9.814004,0.218326,0.218326,0.218326,0.218326,0.218326,0.0,1.0,2.0,3.0,4.0,3360.254784,3359.717143,3359.985964,3360.075570,3360.120374,1945.349031,1793.848041,1813.992868,1839.545175,1803.233030,1414.905753,1565.869102,1545.993095,1520.530396,1556.887344,0.0,0.0,0.0,0.0,0.0
1,38.501936,38.501936,38.501936,38.501936,38.501936,9.827432,11.082343,9.398534,10.787613,9.590578,0.269459,0.269459,0.269459,0.269459,0.269459,0.0,1.0,2.0,3.0,4.0,3080.154885,3079.662060,3079.908473,3079.990610,3080.031679,2102.164630,2169.929834,2079.004139,2154.014402,2089.374542,977.990255,909.732226,1000.904334,925.976208,990.657137,0.0,0.0,0.0,0.0,0.0
2,36.430223,36.430223,36.430223,36.430223,36.430223,10.683613,9.465286,9.746658,11.514564,9.775693,0.246063,0.246063,0.246063,0.246063,0.246063,0.0,1.0,2.0,3.0,4.0,2914.417879,2913.951572,2914.184726,2914.262443,2914.301302,2011.956641,1946.166979,1961.361063,2056.828020,1962.928951,902.461238,967.784593,952.823663,857.434424,951.372351,0.0,0.0,0.0,0.0,0.0
3,35.938170,35.938170,35.938170,35.938170,35.938170,11.297559,9.698321,11.887106,9.470754,10.222731,0.228957,0.228957,0.228957,0.228957,0.228957,0.0,1.0,2.0,3.0,4.0,2875.053640,2874.593631,2874.823636,2874.900304,2874.938638,1945.345213,1858.986392,1977.180773,1846.697727,1887.304518,929.708427,1015.607239,897.642862,1028.202576,987.634120,0.0,0.0,0.0,0.0,0.0
4,40.896125,40.896125,40.896125,40.896125,40.896125,12.626423,11.132050,10.156170,15.687816,8.669442,0.197422,0.197422,0.197422,0.197422,0.197422,0.0,1.0,2.0,3.0,4.0,3271.689980,3271.166510,3271.428245,3271.515490,3271.559112,1833.190365,1752.494255,1699.796732,1998.505620,1619.513397,1438.499615,1518.672254,1571.631513,1273.009870,1652.045715,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34.969811,34.969811,34.969811,34.969811,34.969811,8.622859,8.644766,11.329381,9.667066,11.481153,0.235000,0.235000,0.235000,0.235000,0.235000,0.0,1.0,2.0,3.0,4.0,2797.584858,2797.137245,2797.361051,2797.435654,2797.472955,1836.153197,1837.336159,1982.305420,1892.540398,1990.501104,961.431661,959.801086,815.055631,904.895256,806.971851,0.0,0.0,0.0,0.0,0.0
996,46.920566,46.920566,46.920566,46.920566,46.920566,9.321047,9.542767,9.193690,10.733448,9.068032,0.266532,0.266532,0.266532,0.266532,0.266532,0.0,1.0,2.0,3.0,4.0,3753.645305,3753.044721,3753.345013,3753.445110,3753.495159,2057.752878,2069.725771,2050.875594,2134.022550,2044.090049,1695.892426,1683.318950,1702.469419,1619.422561,1709.405110,0.0,0.0,0.0,0.0,0.0
997,28.807942,28.807942,28.807942,28.807942,28.807942,9.580140,11.951050,11.000270,9.058203,9.709999,0.246736,0.246736,0.246736,0.246736,0.246736,0.0,1.0,2.0,3.0,4.0,2304.635361,2304.266619,2304.450990,2304.512447,2304.543175,1956.290774,2084.319925,2032.977793,1928.106156,1963.303158,348.344587,219.946694,271.473197,376.406291,341.240017,0.0,0.0,0.0,0.0,0.0
998,50.122574,50.122574,50.122574,50.122574,50.122574,8.609420,10.107355,10.533310,8.578442,10.553905,0.202943,0.202943,0.202943,0.202943,0.202943,0.0,1.0,2.0,3.0,4.0,4009.805892,4009.164323,4009.485107,4009.592036,4009.645500,1648.472968,1729.361468,1752.363017,1646.800130,1753.475164,2361.332924,2279.802855,2257.122090,2362.791905,2256.170336,0.0,0.0,0.0,0.0,0.0
999,42.452707,42.452707,42.452707,42.452707,42.452707,8.940336,9.688830,9.116140,10.067195,9.005488,0.241124,0.241124,0.241124,0.241124,0.241124,0.0,1.0,2.0,3.0,4.0,3396.216573,3395.673178,3395.944876,3396.035441,3396.080724,1889.011340,1929.430020,1898.504735,1949.861693,1892.529558,1507.205233,1466.243158,1497.440141,1446.173748,1503.551167,0.0,0.0,0.0,0.0,0.0

In [12]:
from obj import obj_mestrado_victor
tempos = list(range(0, 101, 20))
dados_viga = {'h (m)': 0.50, 'b_w (m)': 0.20, 'm_rd (kN.m)': 30, 'a_s (m2)': 1E-4, 'gamma_c': 1.00, 'gamma_s': 1.00, 'gamma_f': 1.00}
none_variable = {'dados_viga': dados_viga, 'time analysis': tempos}
g = {'type': 'normal', 'parameters': {'mean': 1.06*20, 'sigma': 0.12*1.06*20}, 'stochastic variable': False}
q = {'type': 'gumbel max', 'parameters': {'mean': 0.21*5, 'sigma': 0.21*0.76*5}, 'stochastic variable': True}
f_ck = {'type': 'normal', 'parameters': {'mean': 1.22*25000, 'sigma': 0.15*1.22*25000}, 'stochastic variable': False}
f_yk = {'type': 'normal', 'parameters': {'mean': 1.22*500000, 'sigma': 0.04*1.22*500000}, 'stochastic variable': False}
teta_r = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
teta_s = {'type': 'normal', 'parameters': {'mean': 1, 'sigma': 0.05}, 'stochastic variable': False}
var = [g, q, f_ck, f_yk, teta_r, teta_s]

# PAREpy setup
setup = {
            'number of samples': 500,
            'numerical model': {'model sampling': 'mcs-time', 'time steps': len(none_variable['time analysis'])},
            'variables settings': var,
            'number of state limit functions or constraints': 1,
            'none variable': none_variable,
            'objective function': obj_mestrado_victor,
            'name simulation': 'victor',
        }

results_aux, pf_aux, beta_aux = sampling_algorithm_structural_analysis(setup)
results_aux

10:54:00 - Checking inputs completed!
10:54:00 - Started State Limit Function evaluation (g)...
10:54:03 - Finished State Limit Function evaluation (g) in 2.67e+00 seconds!
10:54:03 - Started evaluation beta reliability index and failure probability...
10:54:03 - Finished evaluation beta reliability index and failure probability in 1.13e-02 seconds!
10:54:03 - Voilà!!!!....simulation results are saved in victor_MCS-TIME_20250319-105403.txt

,X_0_t=0,X_0_t=1,X_0_t=2,X_0_t=3,X_0_t=4,X_0_t=5,X_1_t=0,X_1_t=1,X_1_t=2,X_1_t=3,X_1_t=4,X_1_t=5,X_2_t=0,X_2_t=1,X_2_t=2,X_2_t=3,X_2_t=4,X_2_t=5,X_3_t=0,X_3_t=1,X_3_t=2,X_3_t=3,X_3_t=4,X_3_t=5,X_4_t=0,X_4_t=1,X_4_t=2,X_4_t=3,X_4_t=4,X_4_t=5,X_5_t=0,X_5_t=1,X_5_t=2,X_5_t=3,X_5_t=4,X_5_t=5,STEP_t_0,STEP_t_1,STEP_t_2,STEP_t_3,STEP_t_4,STEP_t_5,R_0_t=0,R_0_t=1,R_0_t=2,R_0_t=3,R_0_t=4,R_0_t=5,S_0_t=0,S_0_t=1,S_0_t=2,S_0_t=3,S_0_t=4,S_0_t=5,G_0_t=0,G_0_t=1,G_0_t=2,G_0_t=3,G_0_t=4,G_0_t=5,I_0_t=0,I_0_t=1,I_0_t=2,I_0_t=3,I_0_t=4,I_0_t=5
0,18.071973,18.071973,18.071973,18.071973,18.071973,18.071973,2.598088,3.165496,0.143658,2.601637,1.982911,0.772069,24624.257088,24624.257088,24624.257088,24624.257088,24624.257088,24624.257088,605632.277837,605632.277837,605632.277837,605632.277837,605632.277837,605632.277837,0.929400,0.929400,0.929400,0.929400,0.929400,0.929400,1.010804,1.010804,1.010804,1.010804,1.010804,1.010804,0.0,1.0,2.0,3.0,4.0,5.0,24.922178,24.373890,22.729027,19.987587,16.149572,11.214980,20.893382,21.466921,18.412434,20.896969,20.271559,19.047635,4.028796,2.906969,4.316593,-0.909382,-4.121987,-7.832654,0.0,0.0,0.0,1.0,1.0,1.0
1,16.515914,16.515914,16.515914,16.515914,16.515914,16.515914,0.041623,1.784196,2.149387,0.938342,0.304431,1.178763,31779.379779,31779.379779,31779.379779,31779.379779,31779.379779,31779.379779,598445.596253,598445.596253,598445.596253,598445.596253,598445.596253,598445.596253,0.951921,0.951921,0.951921,0.951921,0.951921,0.951921,1.014427,1.014427,1.014427,1.014427,1.014427,1.014427,0.0,1.0,2.0,3.0,4.0,5.0,25.319763,24.762728,23.091624,20.306450,16.407206,11.393893,16.796418,18.564132,18.934592,17.706075,17.063018,17.949964,8.523345,6.198596,4.157032,2.600375,-0.655811,-6.556071,0.0,0.0,0.0,0.0,1.0,1.0
2,20.599300,20.599300,20.599300,20.599300,20.599300,20.599300,0.915647,0.942996,0.801555,1.862727,0.489147,1.892042,33388.722395,33388.722395,33388.722395,33388.722395,33388.722395,33388.722395,622142.267477,622142.267477,622142.267477,622142.267477,622142.267477,622142.267477,0.981593,0.981593,0.981593,0.981593,0.981593,0.981593,0.990670,0.990670,0.990670,0.990670,0.990670,0.990670,0.0,1.0,2.0,3.0,4.0,5.0,27.146386,26.549165,24.757504,21.771401,17.590858,12.215874,21.314214,21.341308,21.201187,22.252457,20.891693,22.281499,5.832172,5.207858,3.556317,-0.481056,-3.300835,-10.065626,0.0,0.0,0.0,1.0,1.0,1.0
3,19.618241,19.618241,19.618241,19.618241,19.618241,19.618241,0.102181,2.678796,0.995088,0.254500,3.329388,0.239190,30734.823858,30734.823858,30734.823858,30734.823858,30734.823858,30734.823858,617542.471343,617542.471343,617542.471343,617542.471343,617542.471343,617542.471343,1.053906,1.053906,1.053906,1.053906,1.053906,1.053906,1.008020,1.008020,1.008020,1.008020,1.008020,1.008020,0.0,1.0,2.0,3.0,4.0,5.0,28.902816,28.266954,26.359368,23.180058,18.729025,13.006267,19.878587,22.475868,20.778656,20.032128,23.131678,20.016695,9.024229,5.791086,5.580712,3.147930,-4.402653,-7.010428,0.0,0.0,0.0,0.0,1.0,1.0
4,21.245548,21.245548,21.245548,21.245548,21.245548,21.245548,1.677288,0.531548,0.728174,1.093982,0.077963,1.005925,32263.436196,32263.436196,32263.436196,32263.436196,32263.436196,32263.436196,638237.484140,638237.484140,638237.484140,638237.484140,638237.484140,638237.484140,1.050800,1.050800,1.050800,1.050800,1.050800,1.050800,0.943853,0.943853,0.943853,0.943853,0.943853,0.943853,0.0,1.0,2.0,3.0,4.0,5.0,29.789501,29.134132,27.168025,23.891180,19.303596,13.405275,21.635793,20.554382,20.739968,21.085238,20.126265,21.002125,8.153707,8.579749,6.428056,2.805941,-0.822668,-7.596850,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,18.299188,18.299188,18.299188,18.299188,18.299188,18.299188,0.214200,1.618642,0.269698,2.271317,0.013333,0.826307,29082.486888,29082.486888,29082.486888,29082.486888,29082.486888,29082.486888,602685.582896,602685.582896,602685.582896,602685.582896,602685.582896,602685.582896,0.942071,0.942071,0.942071,0.942071,0.942071,0.942071,1.024010,1.024010,1.024010,1.024010,1.024010,1.024010,0.0,1.0,2.0,3.0,4.0,5.0,25.203705,24.649224,22.985779,20.213372,16.332001,11.341667,18.957902,20.396065,19.014733,21.064411,18.752211,19.584705,6.245804,4.253159,3.971047,-0.851039,-2.420210,-8.243038,0.0,0.0,0.0,1.0,1.0,1.0
496,15.653172,15.653172,15.653172,15.653172,15.653172,15.653172,0.049393,1.013569,1.014696,1.406370,2.121915,0.120013,33018.297293,33018.297293,33018.297293,33018.297293,33018.297293,33018.297293,595052.632087,595052.632087,595052.632087,595052.632087,595052.632087,595052.632087,0.862755,0.862755,0.862755,0.862755,0.862755,0.862755,1.031785,1.031785,1.031785,1.031785,1.031785,1.031785,0.0,1.0,2.0,3.0,4.0,5.0,22.830184,22.327920,20.821127,18.309807,14.793959,10.273583,16.201668,17.196491,17.197653,17.601777,18.340065,16.274533,6.628515,5.131429,3.623475,0.708030,-3.546106,-6.000950,0.0,0.0,0.0,0.0,1.0,1.0
497,22.204934,22.204934,22.204934,22.204934,22.204934,22.204934,1.290038,0.503401,0.541976,1.065544,3.560769,0.289232,32278.677300,32278.677300,32278.677300,32278.677300,32278.677300,32278.677300,591913.028076,591913.028076,591913.028076,591913.028076,591913.028076,591913.028076,0.910518,0.910518,0.910518,0.910518,0.910518,0.910518,0.956493,0.956493,0.956493,0.956493,0.956493,0.956493,0.0,1.0,2.0,3.0,4.0,5.0,23.961956,23.434793,21.853304,19.217489,15.527348,10.782880,22.472786,21.720373,21.757270,22.258060,24.644726,21.515523,1.489170,1.714420,0.096034,-3.040571,-9.117378,-10.732642,0.0,0.0,0.0,1.0,1.0,1.0
498,20.808425,20.808425,20.808425,20.808425,20.808425,20.808425,1.080086,1.161766,0.627561,1.253370,1.301922,3.390886,25749.561361,25749.561361,25749.561361,25749.561361,25749.561361,25749.561361,583707.549092,583707.549092,583707.549092,583707.549092,583707.549092,583707.549092,0.967264,0.967264,0.967264,0.967264,0.967264,0.967264,1.043014,1.043014,1.043014,1.043014,1.043014,1.043014,0.0,1.0,2.0,3.0,4.0,5.0,25.030547,24.479875,22.827859,20.074499,16.219794,11.263746,22.830030,22.915224,22.358040,23.010768,23.061408,25.240227,2.200517,1.564651,0.469819,-2.936269,-6.841614,-13.976481,0.0,0.0,0.0,1.0,1.0,1.0
499,22.195433,22.195433,22.195433,22.195433,22.195433,22.195433,1.019476,-0.248300,-0.229609,0.357196,2.876294,3.095707,35612.837508,35612.837508,35612.837508,35612.837508,35612.837508,35612.837508,623566.918808,623566.918808,623566.918808,623566.918808,623566.918808,623566.918808,1.018178,1.018178,1.018178,1.018178,1.018178,1.018178,0.951100,0.951100,0.951100,0.951100,0.951100,0.951100,0.0,1.0,2.0,3.0,4.0,5.0,28.243640,27.622280,25.758200,22.651399,18.301879,12.709638,22.079702,20.873920,20.891697,21.449807,23.845721,24.054406,6.163938,6.748360,4.866502,1.201592,-5.543843,-11.344768,0.0,0.0,0.0,0.0,1.0,1.0

In [ ]:
setup = {
            'number of samples': 500,
            'numerical model': {'model sampling': 'mcs-time', 'time steps': len(none_variable['time analysis'])},
            'variables settings': var,
            'number of state limit functions or constraints': 1,
            'none variable': none_variable,
            'objective function': obj_mestrado_victor,
            'name simulation': 'victor',
        }

res = sampling_algorithm_structural_analysis_kernel(setup)
res

0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100
0
20
40
60
80
100

ValueError: Length mismatch: Expected axis has 11 elements, new values have 10 elements